export const CREATE = 'create'
export const READ = 'read'
export const WRITE = 'write'
export const DELETE = 'delete'
export const GENERAL = 'general'
export const APPROVE = 'approve'
export const ROLE = 'role'
